### ISSUE TITLE
"Object `%>%` is not exported by 'namespace:tibble'.

### ISSUE THREAD

**Issue by strazto** [r-prof/profile#11]
Hi there. 
This package depends on tibble > 3.0.0 , as it attemtps to import the pipe from tibble.

This reexport was only added in version 3.0.0 , as seen in the following blame.

https://github.com/tidyverse/tibble/blame/a57ad4aec268d511efa0f8479b1884c9d339c53c/NEWS.md#L185

This minimum requirement should be specified in the DESCRIPTION, or, better yet, the source of the import should be changed to `magrittr`, rather than an intermediate package that reexports / imports `magrittr` operators. 

As in:

```r
#' Pipe operator
#'
#' See \code{magrittr::\link[magrittr:pipe]{\%>\%}} for details.
#'
#' @name %>%
#' @rdname pipe
#' @keywords internal
#' @export
#' @importFrom magrittr %>%
#' @usage lhs \%>\% rhs
NULL

#' Backpipe operator
#'
#' See \code{magrittr::\link[magrittr:pipe]{\%<>\%}} for details.
#'
#' @name %<>%
#' @rdname pipe
#' @keywords internal
#' @export
#' @importFrom magrittr %<>%
#' @usage lhs \%<>\% rhs
NULL
```

`usethis::use_pipe(export = FALSE)` accomplishes this, if you don't also want to reexport.

**Comment by krlmlr** [comment]
Good catch, thanks!
