### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by wlandau** [r-prof/profile#7]
I have been struggling to profile `drake` for a long time because of https://github.com/rstudio/profvis/issues/104, and this weekend, `profile` helped me really break through: https://github.com/ropensci/drake/issues/647, https://github.com/wlandau/drake-examples/tree/master/overhead. A big piece of the solution was `pprof`'s ability to spin up a Jupyter-like web server to display interactive visuals: `pprof -http=0.0.0.0:8080 output_from_write_pprof.proto`.

Do you think a front-end to this functionality would fall in scope for `profile` or maybe another package in the `r-prof` org? In my opinion, it could be a really useful high-performance alternative to `profvis`.

**Comment by krlmlr** [comment]
Thanks. The README for _jointprof_, https://r-prof.github.io/jointprof/, has an example that uses `system2()` to achieve this. Are you suggesting to add a wrapper around the shell commands?

**Comment by wlandau** [comment]
That README is really helpful. When I last tried `jointprof` for an Rcpp-powered project at work, it was having trouble combining the R results with the C results, but that problem appears to be fixed now.

I think a wrapper around `system2()` would add convenience, draw more attention to the interactive visuals, and educate users on how to set the hostname/IP and port. Admittedly, I struggled with this last bit because I was working through an ssh session and had to use a different computer to run the browser. Jupyter notebooks are nice because they give you a link that just works, and `pprof` by itself is not as helpful.

**Comment by wlandau** [comment]
Just realized `find_pprof()` will come in handy, so maybe `jointprof` is a better place for the implementation. Moving to https://github.com/r-prof/jointprof/issues/35.
